POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "okan@gmail.com",
    "password": "123456"
}

### Create User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "okan@test.com",
    "fullName":"okan yesil",
    "password": "123456"
}

### Test 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "okan@test.com",
    "password": "123456"
}

### Test jwt

GET http://localhost:3000/profile
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9rYW5AdGVzdC5jb20iLCJzdWIiOjEsImlhdCI6MTY1OTg1NjQ1MSwiZXhwIjoxNjU5ODU3MzUxfQ.gbIS3h7mfJNJtxeyXvmhxXgUo0JYq3xZB1m_20xrF1o

